"""add_mcq_options_to_quiz_session

Revision ID: 0b7dbae2a424
Revises: 9fd51059f934
Create Date: 2026-03-02 00:24:05.164696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7dbae2a424'
down_revision: Union[str, Sequence[str], None] = '9fd51059f934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
