"""Add sura_name and sura_type to Quran table

Revision ID: 4cd0ac7e167f
Revises: a6e607183d49
Create Date: 2026-02-27 10:46:06.050034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd0ac7e167f'
down_revision: Union[str, Sequence[str], None] = 'a6e607183d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran', sa.Column('sura_name', sa.String(), nullable=False))
    op.add_column('quran', sa.Column('sura_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quran', 'sura_type')
    op.drop_column('quran', 'sura_name')
    # ### end Alembic commands ###
