"""add telegram link tokens table

Revision ID: 5cff66270427
Revises: 5b4582208c4c
Create Date: 2026-02-11 02:25:58.342530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cff66270427'
down_revision: Union[str, Sequence[str], None] = '5b4582208c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_users_chat_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_user_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index(op.f('ix_telegram_link_tokens_token'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_user_id'), table_name='telegram_link_tokens')
    op.drop_table('telegram_link_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_link_tokens',
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('telegram_link_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('telegram_link_tokens_pkey'))
    )
    op.create_index(op.f('ix_telegram_link_tokens_user_id'), 'telegram_link_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_telegram_link_tokens_token'), 'telegram_link_tokens', ['token'], unique=False)
    op.create_table('telegram_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('telegram_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('telegram_users_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telegram_users_pkey'))
    )
    op.create_index(op.f('ix_telegram_users_user_id'), 'telegram_users', ['user_id'], unique=True)
    op.create_index(op.f('ix_telegram_users_id'), 'telegram_users', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_users_chat_id'), 'telegram_users', ['chat_id'], unique=True)
    # ### end Alembic commands ###
