"""Add KnowledgeBase and Quran settings

Revision ID: 7115871c3682
Revises: 4cd0ac7e167f
Create Date: 2026-02-27 11:11:29.565825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7115871c3682'
down_revision: Union[str, Sequence[str], None] = '4cd0ac7e167f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE questionmodeenum ADD VALUE IF NOT EXISTS 'PLAIN_TEXT'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active_module', sa.Enum('VOCABULARY', 'QURAN', name='knowledgebaseenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_knowledge_base_id'), 'user_knowledge_base', ['id'], unique=False)
    op.create_table('user_quran_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sura_no', sa.Integer(), nullable=False),
    sa.Column('verse_interval', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_quran_settings_id'), 'user_quran_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quran_settings_id'), table_name='user_quran_settings')
    op.drop_table('user_quran_settings')
    op.drop_index(op.f('ix_user_knowledge_base_id'), table_name='user_knowledge_base')
    op.drop_table('user_knowledge_base')
    # ### end Alembic commands ###
