"""add user progress relationships

Revision ID: 7e295fe7768c
Revises: 
Create Date: 2026-02-04 21:11:32.242688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e295fe7768c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Question History
    with op.batch_alter_table('question_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    
    op.execute("UPDATE question_history SET user_id = 1")

    # Quiz Sessions
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    op.execute("UPDATE quiz_sessions SET user_id = 1")

    # User Progress
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    op.execute("UPDATE user_progress SET user_id = 1")

    # Users
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(), nullable=True))
        # Use existing index creation or batch Create Index? 
        # For SQLite batch op, create_index is supported.
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id'), ['telegram_chat_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id'))
        batch_op.drop_column('telegram_chat_id')

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_word_progress', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_progress_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quiz_sessions_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('question_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_question_history_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
