"""Add attempt to QuizSession

Revision ID: 9fd51059f934
Revises: b4156ee2d22f
Create Date: 2026-03-01 23:33:01.758312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd51059f934'
down_revision: Union[str, Sequence[str], None] = 'b4156ee2d22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('attempt', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'attempt')
    # ### end Alembic commands ###
