"""update scheduler settings

Revision ID: a523dbaa062c
Revises: e17531fa72e5
Create Date: 2026-02-14 15:34:08.586842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a523dbaa062c'
down_revision: Union[str, Sequence[str], None] = 'e17531fa72e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_settings', sa.Column('start_time_utc', sa.Time(), nullable=False))
    op.add_column('scheduler_settings', sa.Column('end_time_utc', sa.Time(), nullable=False))
    op.drop_column('scheduler_settings', 'end_time')
    op.drop_column('scheduler_settings', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_settings', sa.Column('start_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('scheduler_settings', sa.Column('end_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_column('scheduler_settings', 'end_time_utc')
    op.drop_column('scheduler_settings', 'start_time_utc')
    # ### end Alembic commands ###
