"""Add Quran table

Revision ID: a6e607183d49
Revises: a523dbaa062c
Create Date: 2026-02-27 10:20:48.617096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e607183d49'
down_revision: Union[str, Sequence[str], None] = 'a523dbaa062c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sura_no', sa.Integer(), nullable=False),
    sa.Column('verse_no', sa.Integer(), nullable=False),
    sa.Column('verse', sa.String(), nullable=False),
    sa.Column('bengali_translation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quran_id'), 'quran', ['id'], unique=False)
    op.create_index(op.f('ix_quran_sura_no'), 'quran', ['sura_no'], unique=False)
    op.create_index(op.f('ix_quran_verse_no'), 'quran', ['verse_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quran_verse_no'), table_name='quran')
    op.drop_index(op.f('ix_quran_sura_no'), table_name='quran')
    op.drop_index(op.f('ix_quran_id'), table_name='quran')
    op.drop_table('quran')
    # ### end Alembic commands ###
