"""add next_execution_time fields in the scheduler_settings

Revision ID: ad7fced2f490
Revises: d4a7a553d00c
Create Date: 2026-02-14 13:09:44.281804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7fced2f490'
down_revision: Union[str, Sequence[str], None] = 'd4a7a553d00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_settings', sa.Column('next_execution_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_settings', 'next_execution_time')
    # ### end Alembic commands ###
