"""enforce user_id constraints

Revision ID: cc1723eda056
Revises: 7e295fe7768c
Create Date: 2026-02-04 21:16:29.350492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1723eda056'
down_revision: Union[str, Sequence[str], None] = '7e295fe7768c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_question_history_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_question_history_users_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quiz_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_quiz_sessions_users_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_word_progress', ['user_id', 'word_id'])
        batch_op.create_foreign_key('fk_user_progress_users_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_word_progress', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_progress_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quiz_sessions_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('question_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_question_history_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
