"""add_user_id_to_scheduler_settings

Revision ID: d4a7a553d00c
Revises: 40c066eda50a
Create Date: 2026-02-14 12:08:29.592483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a7a553d00c'
down_revision: Union[str, Sequence[str], None] = '40c066eda50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_settings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'scheduler_settings', ['user_id'])
    op.create_foreign_key(None, 'scheduler_settings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduler_settings', type_='foreignkey')
    op.drop_constraint(None, 'scheduler_settings', type_='unique')
    op.drop_column('scheduler_settings', 'user_id')
    # ### end Alembic commands ###
