"""maxlength is set to 255 in hashed password

Revision ID: f25426ae9ac3
Revises: cc1723eda056
Create Date: 2026-02-04 22:58:53.119682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25426ae9ac3'
down_revision: Union[str, Sequence[str], None] = 'cc1723eda056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
